### ISSUE TITLE
Add API to setup role parameter

### ISSUE THREAD

**Issue by mengelbart** [mengelbart/moqtransport#11]

**Comment by boserohan91** [comment]
I would like to submit a PR for this. Please could you point me to the right direction in the codebase.

**Comment by mengelbart** [comment]
I think for now, it could be an argument to _[newClientPeer](https://github.com/mengelbart/moqtransport/blob/5405dea98205d40767203796de486f9f12c42997/peer.go#L121)_ and then propagated up to the public Dial API. Long term, I am thinking about moving the setup message exchange to the _Peer.Run_ call, and then we could add a more flexible configuration to the client between creating a client and doing the setup handshake.

**Comment by mengelbart** [comment]
Done in #18
