### ISSUE TITLE
Client should not wait on announce

### ISSUE THREAD

**Issue by TimEvens** [mengelbart/moqtransport#143]
https://github.com/mengelbart/moqtransport/blob/07e66c9b7003fc0e20262ce0eae11de69c5bd304/examples/date-client/main.go#L59

Client doesn't receive announcements.

**Comment by mengelbart** [comment]
Thanks for bringing this up. I removed the announcements from the refactored version of the date server and client. I hope this fixes the issue. Please reopen if it doesn't.
