### ISSUE TITLE
The peer also accept bidirectional streams for receiving objects

### ISSUE THREAD

**Issue by tanghaowillow** [mengelbart/moqtransport#22]
Hi, I find that a peer also accepts bidirectional streams to receive object messages, while the draft says the bidirectional stream is only used as the control stream.

**Comment by mengelbart** [comment]
That is a good point, thanks! Would you like to send a PR?

**Comment by tanghaowillow** [comment]
Yes, happy to help. I guess this just needs remove the code of accepting bidirectional streams.

**Comment by mengelbart** [comment]
Yes, that should be fine for now. The draft says a peer *MAY* close the connection, but it's not required.
